
package:
  name: intermediate_python_project
  version: {{ VERSION }}

source:
  git_url: https://github.com/aleksey-orekhov/intermediate_python_project.git
  git_rev: release/{{ VERSION }}

  
build:
    number: {{ BUILD_NUMBER }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
	
about:
  home: https://anaconda.org/
  license: Creative Commons Attribution 4.0 International License.
  summary: 'smallest packagable python project'

